name: Deploy to VPS

on:
  push:
    branches:
      - main   # đổi nếu bạn dùng branch khác

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          timeout: 120s
          script: |
            set -e
            cd ${{ secrets.VPS_PATH }}
            # đảm bảo branch đúng
            git fetch --all
            git reset --hard origin/${{ secrets.BRANCH }}
            # cài package (dùng npm ci cho reproducible)
            npm ci
            npm run build
            # restart pm2, nếu chưa chạy thì start
            pm2 restart ${{ secrets.PM2_NAME }} || pm2 start npm --name "${{ secrets.PM2_NAME }}" -- start

